name: CICD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  job1:
    name: stage1
    runs-on: ubuntu-latest
    steps:
      - name: print output
        run: hostname
        
  job2:
    name: stage2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: print output
        run: hostname
