name: CICD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  call-workflow-1-in-local-repo:
    uses: ./.github/workflows/stage1.yml
  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/stage2.yml
